config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'
  
  resources :users
  resources :cities
  resources :states
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/state.rb
class State < ApplicationRecord
    has_many :states
    has_many :cities
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :state
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities= City.all
  end

  def show
    @city = City.find(params[:id])
  end

  def edit
    @city = City.find(params[:id])
  end

  def new
    @city = City.new
  end
  
  def create
    @city = City.new(city_params)

    if @city.save
      redirect_to @city
    else
      render :new
    end
  end

  def update
    @city = City.find(params[:id])

    if @city.update(city_params)
      redirect_to @city
    else
      render :edit
    end
  end

  def destroy
    @city = City.find(params[:id])
    @city.destroy

    redirect_to root_path
  end

  private
    def city_params
      params.require(:city).permit(:name, :state_id)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  
  def index
    @states= State.all
  end

  def show
    @state = State.find(params[:id])
  end

  def edit
    @state = State.find(params[:id])
  end

  def new
    @state = State.new
  end
  
  def create
    @state = State.new(state_params)

    if @state.save
      redirect_to @state
    else
      render :new
    end
  end

  def update
    @state = State.find(params[:id])

    if @state.update(state_params)
      redirect_to @state
    else
      render :edit
    end
  end

  def destroy
    @state = State.find(params[:id])
    @state.destroy

    redirect_to root_path
  end

  private
    def state_params
      params.require(:state).permit(:name)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:name , :email , :state_id ,:city_id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= form_with model: city do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :state %>
        <%= f.select(:state_id, State.all.collect {|s| [s.name, s.id]}, {:prompt => 'Select State'}) %>
    </div>

    <div>
        <%= f.submit %>
    </div>
    
<% end %>

app/views/cities/edit.html.erb
<h1>Edit city</h1>

<%= render "form", city: @city %>

app/views/cities/index.html.erb
<div>
    <h1>cities</h1>
</div>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>State</th>
        </tr>
    </thead>


    <tbody>
        <% @cities&.each do |city|%>
            <tr>
                <td><%= city.name %></td>
                <td><%= city.state.name %></td>
                <td><%= link_to 'Show', city %></td>
                <td><%= link_to 'Edit', edit_city_path(city) %></td>
                <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' }%></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'new city', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render "form", city: @city %>

app/views/cities/show.html.erb
<h2>Company Details</h2>

    <P><strong>Name:</strong></P>
    <P><%= @city.name %></P>

    <P><strong>State:</strong></P>
    <P><%= @city.state.name %></P>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/states/_form.html.erb
<%= form_with model: state do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.submit %>
    </div>
    
<% end %>

app/views/states/edit.html.erb
<h1>Edit state</h1>

<%= render "form", state: @state %>

app/views/states/index.html.erb
<div>
    <h1>states</h1>
</div>

<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>


    <tbody>
        <% @states.each do |state|%>
            <tr>
                <td><%= state.name %></td>
                <td><%= link_to 'Show', state %></td>
                <td><%= link_to 'Edit', edit_state_path(state) %></td>
                <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' }%></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'new state', new_state_path %>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render "form", state: @state %>

app/views/states/show.html.erb
<h1>States#show</h1>
<p>Find me in app/views/states/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_with model: user do |f| %>

    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :state %>
        <%= f.select(:state_id, State.all.collect {|s| [s.name, s.id]}, {:prompt => 'Select State'}) %>
    </div>

    <div>
        <%= f.label :city %>
        <%= f.select(:city_id, {}, {:prompt => 'Select City'},{id: 'city'}) %>
    </div>

    <div>
        <%= f.submit %>
    </div>
    
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<div>
    <h1>Users</h1>
</div>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>State</th>
            <th>City</th>
        </tr>
    </thead>


    <tbody>
        <% @users.each do |user|%>
            <tr>
                <td><%= user.name %></td>
                <td><%= user.email %></td>
                <td><%= user.state.name %></td>
                <td><%= user.city.name %></td>
                <td><%= link_to 'Show', user %></td>
                <td><%= link_to 'Edit', edit_user_path(user) %></td>
                <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }%></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'new user', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>